### ISSUE TITLE
sdmTMB area estimates to inform ACL allocation north and south of 36

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/sablefish#4]
The estimated coastwide ACL for sablefish is split into two separate ACLs north and south of 36 degrees North latitude.  The current approach is based on the relative proportion of the biomass estimates from the NWFSC WCGBT from a rolling 5-year average from a VAST model run.  It appears that the 2023-24 harvest specifications retained the estimated split percent conducted in 2019 where the rolling 5-year average was calculated based on the estimates from 2014-2018 where 78.4% of the biomass was estimated to be north of 36 degrees and 21.6% south of 36 degrees.  It is unclear whether the GMT will request new relative biomass estimates to update the ACL proportions based on the most recent sdmTMB model run.  @chantelwetzel-noaa  will reach out to Council staff and GMT to see if these values need to be provided within this update assessment.

**Comment by kellijohnson-NOAA** [comment]
Data were added in [ab373a5](https://github.com/pfmc-assessments/sablefish/commit/ab373a5669f61188f97cf9fc16398701631f2ad1).

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa this issue is done right?

**Comment by chantelwetzel-noaa** [comment]
Yes!  Thank you.
