### ISSUE TITLE
top and bottom 15

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/sablefish#5]
https://github.com/pfmc-assessments/sablefish/blob/aa965e3a642330b5ff3d0e2adbcf5c943f168e3e/presentations/base_results.qmd#L175

I would have expected that these top and bottom 15 estimates would be recruitment deviations.  I think recruits are interesting to see but it is influenced by the population size at the time so they can be more difficult to compare than recruitment deviations. I think we should either replace the recruits with recruitment deviations or we should add two additional tabs for recruitment deviations.  I tried to do this myself but struggled a bit with the code so I thought I would bring you into the conversation before spending too much time on it.

**Comment by kellijohnson-NOAA** [comment]
Fixed in 11d5bb4 and d284c1748bd3be7c35e3f198e743d77eb1814217.
