### ISSUE TITLE
Rerun the R0 profile

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/sablefish#6]
The current R0 profile appears to include two model runs that failed to converge.  The run that appears to have failed to converge is the base model run (R0 ~ 9.8758) where the profile run has a substantially higher likelihood compared to the surrounding runs.  The nwfscDiag package can be used to rerun this single model:

```
nwfscDiag::rerun_profile_vals(mydir = file.path(model_dir, base_name),
           model_settings = model_settings,
           para_name =  "SR_LN(R0)",
           run_num = c(6),
           data_file_nm = "data.ss") 
```

**Comment by kellijohnson-NOAA** [comment]
Fixed with [0d6264a](https://github.com/pfmc-assessments/sablefish/commit/0d6264ad0a9ff37c5630ffc79ef13a8aababb3b1) and some massaging of R_0 == 10.0 (incrementally stepping from 9.9 to 10.0) and R_0 == base (adding more significant digits).
